name: Continuous Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linux:
    name: Linux x86_64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt: ["6.8", "6.10"]

    steps:
      - uses: actions/checkout@v7

      - run: sudo apt install -y libxkbcommon-x11-dev cmake ninja-build build-essential libfreetype-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '${{ matrix.qt }}.*'
          modules: "qthttpserver qtwebsockets"

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j 4

      - name: Print output files
        run: |
          echo "Output files:"
          find build -type f -name "*.so"
