name: Continuous Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt: ["6.8", "6.10"]

    steps:
      - uses: actions/checkout@v7

      - run: sudo apt install -y libxkbcommon-x11-dev cmake ninja-build build-essential libfreetype-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '${{ matrix.qt }}.*'
          modules: "qthttpserver qtwebsockets"

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j 4

      - name: Rename
        run: mv build/plugins/platforms/libqweb.so "libqweb-${{ matrix.qt }}.so"

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: libqweb-${{ matrix.qt }}
          path: libqweb-${{ matrix.qt }}.so

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/download-artifact@v8
        with:
          path: release

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ github.run_number }}
          tag_name: release-${{ github.run_number }}
          files: release/**/libqweb-*.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
